version: '3.8'

services:
  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "${NEXT_PORT}:${NEXT_PORT}"
    depends_on:
      - backend
    networks:
      - webnet

  backend:
    build: ./backend
    env_file: .env
    ports:
      - "${NEST_PORT}:${NEST_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - webnet

  postgres:
    image: postgres:14-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

volumes:
  postgres_data:

networks:
  webnet:
    external: true
